cc_library(
    name = "record",
    srcs = [
        "src/field.cpp", 
        "src/tuple.cpp"
    ],
    hdrs = [
        "include/record/field.hpp", 
        "include/record/tuple.hpp"
    ],
    deps = [
        "//srd/common:common",
    ],
    strip_include_prefix = "include",
    visibility = [
        "//visibility:public"
    ],
)

cc_test(
    name = "field_test",
    srcs = ["test/field_test.cpp"],
    deps = [
        ":record",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "tuple_test",
    srcs = ["test/tuple_test.cpp"],
    deps = [
        ":record",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)