name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Bazelisk
        uses: bazelbuild/setup-bazelisk@v3

      - name: Build
        run: bazelisk build //...

      - name: Test
        run: bazelisk test //tests/... --test_output=all

      - name: Set build status
        if: ${{ success() }}
        run: echo "Build succeeded"

      - name: Set build status
        if: ${{ failure() }}
        run: echo "Build failed"
